excluded:
  - HSERickAppTests
  - HSERickAppUITests

identifier_name:
  excluded:
    - id
    - vc
    - to

line_length:
  warning: 140
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
